import type { Metadata } from "next";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import SSEContextProvider from "@/context/SSEContext";
import {ToastContainer} from "react-toastify"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AppRouterCacheProvider>
        <SSEContextProvider>
          <ToastContainer autoClose={200} />
        {children}
        </SSEContextProvider>
      </AppRouterCacheProvider>
      
      </body>
    </html>
  );
}
